---
- name: Install zsh and dependencies
  become: true
  ansible.builtin.apt:
    name:
    - git-core
    - powerline
    - zsh
    - zsh-syntax-highlighting
    state: present

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "/usr/bin/zsh"

- name: Check for Oh My Zsh
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zs"
  register: ohmyzsh

- name: Install Oh My Zsh
  when: not ohmyzsh.stat.exists
  block:
  - name: Download Oh My Zsh installation script
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh
      mode: 0755

  - name: Run Oh My Zsh installation script
    ansible.builtin.command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"

  - name: Delete Oh My Zsh installation script
    ansible.builtin.file:
      path: /tmp/install_ohmyzsh.sh
      state: absent

- name: Check for dircolors
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.dircolors"
  register: dircolors

- name: Install dircolors
  when: not dircolors.stat.exists
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark"
    dest: "{{ ansible_user_dir }}/.dircolors"
    mode: 0644

- name: Check for powerlevel10k
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: powerlevel10k

- name: Clone powerlevel10k
  when: not powerlevel10k.stat.exists
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    force: true
