---
- hosts: wsl
  ### Go here to edit variables ###
  vars_files:
  - vars/prerequisite_packages.yml
  - vars/tool_versions.yml
  - vars/user_environment.yml
  roles:
  - packages
  - shell
  # - workspace
  - ops
  # - dev
