---
- name: Update package list
  become: true
  ansible.buitin.package:
    update_cache: yes
- name: Upgrade all packages
  become: true
  ansible.buitin.package:
    name: "*"
    state: latest
- name: Install packages
  become: true
  ansible.buitin.apt:
    name: "{{ prerequisite_packages }}"
