---
- name: Add an apt signing key for Ansible
  become: true
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
    dest: /usr/share/keyrings/ansible.gpg
    mode: '0644'
    force: true

- name: Add apt repository for Ansible
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/ansible.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ubuntu_codename }} main"
    state: present
    filename: ansible

- name: Install ansible, ansible-lint and sshpass
  become: true
  ansible.builtin.apt:
    name:
      - ansible
      - ansible-lint
      - sshpass
    state: latest
    update_cache: true
  register: result
  until: result is succeeded
