---
- name: Add an apt signing key for Ansible
  become: true
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
    dest: /etc/apt/trusted.gpg.d/ansible.asc
    mode: '0644'
    force: true

- name: Add apt repository for Ansible
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/ansible.asc] http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ubuntu_codename }} main"
    state: present
    filename: ansible

- name: Install ansible-lint and sshpass
  become: true
  ansible.builtin.apt:
    name:
    - ansible-lint
    - sshpass
    state: latest
    update_cache: true

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    upgrade: yes
    state: latest
