---
- name: Add an apt signing key for Helm
  become: true
  ansible.builtin.get_url:
    url: "https://baltocdn.com/helm/signing.asc"
    dest: /etc/apt/trusted.gpg.d/helm.asc
    mode: '0644'
    force: true

- name: Add apt repository for Helm
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ apt_arch }} signed-by=//etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    filename: helm

- name: Install helm
  become: true
  ansible.builtin.apt:
    name:
    - helm
    state: present
    update_cache: true
