---
- name: Add an apt signing key for Helm
  become: true
  ansible.builtin.get_url:
    url: "https://packages.buildkite.com/helm-linux/helm-debian/gpgkey"
    dest: /usr/share/keyrings/helm.gpg
    mode: '0644'
    force: true

- name: Add apt repository for Helm
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    state: present
    filename: helm

- name: Install Helm
  become: true
  ansible.builtin.apt:
    name:
      - helm
    state: present
    update_cache: yes
  register: result
  until: result is succeeded

- name: Block for bash completion
  when: current_shell == "bash"
  block:
  - name: Add Terraform completion for bash
    become: yes
    ansible.builtin.shell: helm completion bash > /etc/bash_completion.d/helm
    args:
      creates: /etc/bash_completion.d/helm
