---
- name: Add an apt signing key for Kubernetes
  become: true
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
    force: true

- name: Add apt repository for Kubernetes
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name:
      - kubectl
    state: present
    update_cache: true
  register: result
  until: result is succeeded

- name: Block for bash completion
  when: current_shell == "bash"
  block:
    - name: Add Terraform completion for bash
      become: true
      ansible.builtin.shell: kubectl completion bash > /etc/bash_completion.d/kubectl
      args:
        creates: /etc/bash_completion.d/kubectl
