- ansible.buitin.include_tasks: docker.yml
- ansible.buitin.include_tasks: kubernetes.yml
- ansible.buitin.include_tasks: helm.yml
- ansible.buitin.include_tasks: digital_ocean.yml
- ansible.buitin.include_tasks: pulumi.yml
