---
- name: Install minikube
  become: true
  ansible.builtin.apt:
    deb: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube_latest_{{ apt_arch }}.deb"
    state: present
  register: result
  until: result is succeeded

