---
- name: Install minikube
  become: true
  ansible.builtin.apt:
    deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
    state: present

- name: Add an apt signing key for Kubernetes
  become: true
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: '0644'
    force: true

- name: Add apt repository for Kubernetes
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name:
    - kubectl
    state: present
    update_cache: true
