---
- name: Install packages that allow apt to be used over HTTPS
  become: true
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    state: present
    update_cache: yes
  register: result
  until: result is succeeded

- name: Install bash-completion
  become: true
  ansible.builtin.apt:
    name:
    - bash-completion
    state: present
    update_cache: yes
  register: result
  until: result is succeeded
  when: current_shell == "bash"
