---
- name: Download latest pulumi release
  ansible.buitin.get_url:
    url: https://get.pulumi.com/releases/sdk/pulumi-v{{ pulumi_version }}-linux-x64.tar.gz
    dest: /var/tmp/pulumi-{{ pulumi_version }}.tar.gz
- name: Untar pulumi release
  ansible.buitin.unarchive:
    src: /var/tmp/pulumi-{{ pulumi_version }}.tar.gz
    dest: /var/tmp
- name: Add pulumi binary to path
  become: true
  ansible.buitin.copy:
    src: /var/tmp/pulumi/
    dest: /usr/local/bin/
    mode: 0755
