---
- name: Add an apt signing key for Hashicorp apps
  become: true
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add apt repository for Hashicorp apps
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ apt_arch }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Install Terraform
  become: true
  ansible.builtin.apt:
    name:
      - terraform
    state: present
    update_cache: true
  register: result
  until: result is succeeded

- name: Block for bash completion
  when: current_shell == "bash"
  block:
  - name: Add Terraform completion for bash
    become: true
    ansible.builtin.copy:
      dest: /etc/bash_completion.d/terraform
      content: |
        complete -C $(which terraform) terraform
      owner: root
      group: root
      mode: '0644'
