---
- name: Install Ruby dependencies
  become: true
  ansible.buitin.apt:
    name: "{{ ruby_dependencies }}"
  vars:
    ruby_dependencies:
    - build-essential
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - automake
- name: Install Ruby
  ansible.buitin.shell: "asdf install ruby {{ ruby_version }}"
- name: Set global Ruby
  ansible.buitin.shell: "asdf global ruby {{ ruby_version }}"
